version: '3'
services:
  db:
    image: mariadb:10.5
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=borghive
      - MYSQL_USER=borghive
      - MYSQL_PASSWORD=borghive
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  app:
    build:
      context: .
      dockerfile: Dockerfile.base
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - MYSQL_HOST=db
      - MYSQL_DATABASE=borghive
      - MYSQL_USER=borghive
      - MYSQL_PASSWORD=borghive
      - BORGHIVE_ADMIN_PASSWORD=login
    env_file:
      - .env
      - .dev
    volumes:
      - ./src:/app
      - borg-config:/config
      - borg-repos:/repos
      - static:/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile.base
    entrypoint: celery -A core worker -l DEBUG -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DEBUG=True
      - MYSQL_HOST=db
      - MYSQL_DATABASE=borghive
      - MYSQL_USER=borghive
      - MYSQL_PASSWORD=borghive
    env_file:
      - .env
      - .dev
    volumes:
      - ./src:/app
      - borg-config:/config
      - borg-repos:/repos:ro
    depends_on:
      - db

  watcher:
    build:
      context: .
      dockerfile: Dockerfile.base
    entrypoint: /bin/bash -c "/app/manage.py watch_repositories"
    environment:
      - APP_LOG_LEVEL=DEBUG
      - MYSQL_HOST=db
      - MYSQL_DATABASE=borghive
      - MYSQL_USER=borghive
      - MYSQL_PASSWORD=borghive
    restart: 'on-failure'
    volumes:
      - ./src:/app
      - borg-repos:/repos:ro
    depends_on:
      - db

  borg:
    build:
      context: .
      dockerfile: Dockerfile.borg
    depends_on:
      - db
    environment:
      - DEBUG=True
      - MYSQL_HOST=db
      - MYSQL_DATABASE=borghive
      - MYSQL_USER=borghive
      - MYSQL_PASSWORD=borghive
      - BORG_LDAP_HOST=ldap://ldap
      - BORG_LDAP_BASE_DN=dc=borghive,dc=local
      - BORG_LDAP_READONLY_DN=cn=readonly,dc=borghive,dc=local
      - BORG_LDAP_READONLY_USER_PASSWORD=readonly
    volumes:
      - borg-repos:/repos
      - borg-config:/config
      - ./src:/app
    ports:
      - "22:22"

  ldap:
    image: osixia/openldap:latest
    environment:
      - LDAP_ORGANISATION=borghive
      - LDAP_DOMAIN=borghive.local
      - LDAP_ADMIN_PASSWORD=borghive
      - LDAP_READONLY_USER=true
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

  redis:
    image: redis:latest

volumes:
  mariadb-data:
  borg-repos:
  borg-config:
  ldap-data:
  ldap-config:
  static:
