# Generated by Django 3.0.5 on 2020-05-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.AddField(
            model_name='repository',
            name='user',
            field=models.CharField(default='B30efptZ', max_length=8, unique=True),
        ),
    ]
