# Generated by Django 3.0.5 on 2020-05-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0002_auto_20200501_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.CharField(default='fkk8727b', max_length=8, unique=True),
        ),
    ]
