# Generated by Django 3.0.5 on 2020-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0002_auto_20200506_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.AddField(
            model_name='repository',
            name='alert_after_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='n67kbp4i', max_length=8, unique=True),
        ),
    ]
