# Generated by Django 3.0.5 on 2020-05-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0003_auto_20200501_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshpublickey',
            old_name='publicy_key',
            new_name='public_key',
        ),
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.CharField(default='mubfu9fl', max_length=8, unique=True),
        ),
    ]
