# Generated by Django 3.0.7 on 2020-09-19 20:15

from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0003_repo_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorystatistic',
            name='repo_size_unit',
            field=models.CharField(default='MB', max_length=3),
            preserve_default=False,
        )
    ]
