# Generated by Django 3.0.5 on 2020-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0003_auto_20200506_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorystatistic',
            name='last_access',
        ),
        migrations.RemoveField(
            model_name='repositorystatistic',
            name='last_update',
        ),
        migrations.AddField(
            model_name='repository',
            name='last_access',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='8xup462t', max_length=8, unique=True),
        ),
    ]
