# Generated by Django 3.0.5 on 2020-05-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0004_auto_20200501_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='vbuyy3wx', max_length=8, unique=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borghive.RepositoryUser'),
        ),
    ]
