# Generated by Django 3.0.5 on 2020-05-06 17:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borghive', '0004_auto_20200506_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryevent',
            name='event_type',
            field=models.CharField(choices=[('watcher', 'watcher'), ('alert', 'alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='koh8rzv0', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='AlertPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_interval', models.PositiveIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(48)])),
                ('alert_expiration', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(30)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
