# Generated by Django 3.0.5 on 2020-05-06 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borghive', '0005_auto_20200506_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertPreferences',
            new_name='AlertPreference',
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='jevmy2lv', max_length=8, unique=True),
        ),
    ]
