# Generated by Django 3.0.5 on 2020-05-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0006_auto_20200501_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borghive.RepositoryUser'),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='r1zd6x66', max_length=8, unique=True),
        ),
    ]
