# Generated by Django 3.0.5 on 2020-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0007_auto_20200502_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryuser',
            name='password',
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='38074yde', max_length=8, unique=True),
        ),
    ]
