# Generated by Django 3.0.5 on 2020-05-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0008_auto_20200502_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='user',
            new_name='repo_user',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='keys',
            new_name='ssh_keys',
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='bi3d22ke', max_length=8, unique=True),
        ),
    ]
