# Generated by Django 3.0.5 on 2020-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0009_auto_20200502_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('repo_size', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='8dh7gurz', max_length=8, unique=True),
        ),
    ]
