# Generated by Django 3.0.5 on 2020-05-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0010_auto_20200502_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorystatistic',
            name='repo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='borghive.Repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='s01w7j20', max_length=8, unique=True),
        ),
    ]
