# Generated by Django 3.0.5 on 2020-05-03 21:23

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0011_auto_20200502_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorystatistic',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 21, 23, 36, 753211, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repositorystatistic',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='0asnt00k', max_length=8, unique=True),
        ),
    ]
