# Generated by Django 3.0.5 on 2020-05-04 11:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0012_auto_20200503_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshpublickey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='n6o8b1b6', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='sshpublickey',
            name='public_key',
            field=models.TextField(max_length=2048, validators=[django.core.validators.RegexValidator(regex='ssh-([a-zA-Z0-9]+) (AAAA[0-9A-Za-z+/=]+) ([\\w\\-@]+)')]),
        ),
    ]
