# Generated by Django 3.0.5 on 2020-05-04 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0014_auto_20200504_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='cjabdppu', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='sshpublickey',
            name='public_key',
            field=models.TextField(max_length=2048, validators=[django.core.validators.RegexValidator(message='SSH Public Key should match format: ssh-xxx AAAA... comment', regex='ssh-([a-zA-Z0-9]+) (AAAA[0-9A-Za-z+/=]+) ([\\w\\-@]+)')]),
        ),
    ]
