# Generated by Django 3.0.5 on 2020-05-04 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borghive', '0016_auto_20200504_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorystatistic',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sshpublickey',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(default='4pvqps8g', max_length=8, unique=True),
        ),
    ]
